start = 
  (
  "bowtie2" /\s*/
    {
        (
        "-x" /\s*/
        db:/\S+/ /\s*/
        )
    |
        (
        "-1" /\s*/
        "fq_input_forward!!/\S+/" /\s*/
        )
    }
  $
  )
 ; 
