start = 
  bowtie2 | 
  bowtie2_00 | 
  bowtie2_01 | 
  bowtie2_02 | 
  bowtie2_03 | 
  bowtie2_04 ;

bowtie2 = "bowtie2" $ ;

bowtie2_00 = "bowtie2" { /\s+/ bowtieoptions} /\s+/ "-x" /\s+/ database /\s+/
    "-1" /\s+/ forward_reads /\s+/ "-2" /\s+/ reverse_reads /\s+/ "-S" /\s+/
    samout $ ;

bowtie2_01 = "bowtie2" { /\s+/ bowtieoptions} /\s+/ "-x" /\s+/ database /\s+/
    "-1" /\s+/ forward_reads /\s+/ "-2" /\s+/ reverse_reads $ ;

bowtie2_02 = "bowtie2" { /\s+/ bowtieoptions} /\s+/ "-x" /\s+/ database /\s+/
    "-U" /\s+/ reads /\s+/ "-S" /\s+/ samout $ ;

bowtie2_03 = "bowtie2" { /\s+/ bowtieoptions} /\s+/ "-x" /\s+/ database /\s+/
    "-U" /\s+/ reads $ ;

bowtie2_04 = "bowtie2" $ ;


(* files *)
samout = samout+:/\S+/ ; 
forward_reads = forward_reads+:/\S+/ ; 
reverse_reads = reverse_reads+:/\S+/ ; 
reads = reads+:/\S+/ ; 
database = database+:/\S+/ ; 


(* options *)
bowtieoptions = (
  bowtieoptions_flag
  | "--qseq"
  | "-s" /\s+/ int
  | "--skip" /\s+/ int
  | "-u" /\s+/ int
  | "--upto" /\s+/ int
  | "-5" /\s+/ int
  | "--trim5" /\s+/ int
  | "-3" /\s+/ int
  | "--trim3" /\s+/ int
  | "--phred33"
  | "--phred64"
  | "--int-quals"
  | "--very-fast"
  | "--fast"
  | "--sensitive"
  | "--very-sensitive"
  | "--very-fast-local"
  | "--fast-local"
  | "--sensitive-local"
  | "--very-sensitive-local"
  | "-N" /\s+/ int
  | "-L" /\s+/ int
  | "-i" /\s+/ str
  | "--n-ceil" /\s+/ str
  | "--dpad" /\s+/ int
  | "--gbar" /\s+/ int
  | "--ignore-quals"
  | "--nofw"
  | "--norc"
  | "--no-1mm-upfront"
  | "--end-to-end"
  | "--local"
  | "--ma" /\s+/ int
  | "--mp" /\s+/ int
  | "--np" /\s+/ int
  | "--rdg" /\s+/ twoints
  | "--rfg" /\s+/ twoints
  | "--score-min" /\s+/ str
  | "-k" /\s+/ int
  | "--all"
  | "-D" /\s+/ int
  | "-R" /\s+/ int
  | "-I" /\s+/ int
  | "--minins" /\s+/ int
  | "-X" /\s+/ int
  | "--maxins" /\s+/ int
  | "--fr"
  | "--rf"
  | "--ff"
  | "--no-mixed"
  | "--no-discordant"
  | "--no-dovetail"
  | "--no-contain"
  | "--no-overlap"
  | "--time"
  | "--un" /\s+/ path
  | "--al" /\s+/ path
  | "--un-conc" /\s+/ path
  | "--al-conc" /\s+/ path
  | "--un-gz" /\s+/ path
  | "--quiet"
  | "--met-file" /\s+/ file
  | "--met-stderr"
  | "--met" /\s+/ int
  | "--no-unal"
  | "--no-head"
  | "--no-sq"
  | "--rg-id" /\s+/ str
  | "--rg" /\s+/ str
  | "--omit-sec-seq"
  | "-p" /\s+/ int
  | "--threads" /\s+/ int
  | "--reorder"
  | "--mm"
  | "--qc-filter"
  | "--seed" /\s+/ int
  | "--non-deterministic"
  | "--version"
  | "--help"
  ) ; 

bowtieoptions_flag = "-" { "q"
        | "f"
        | "r"
        | "c"
        | "a"
        | "t"
        | "h" }+;


(* other *)
twoints = twoints+:/[0-9]+,[0-9]/ ; 


(* Misc *)
file = /\S+/ ;
path = file ; 
int = /[0-9]+/ ;
integer = int ;
float = /[0-9\.]+/ ;
string = ( /"[^"]*"/ | /'[^']*'/ | /\S+/ ) ;
str = string ;
