start = 
  (
  "cramtools"
    {
        (
        "cram"
          {
              (
              "--capture-tags"
              /.*/
              )
          |
          "--capture-all-tags"
          |
          "--encrypt"
          |
              (
              "-I"
              input_bam:/.*.bam/
              )
          |
              (
              "-O"
              output_cram:/.*.cram/
              )
          |
              (
              "-R"
              input_reference_genome:/.*/
              )
          }
        )
    |
        (
        "bam"
          {
            (
            "--password"
            |
            "-p"
            )
          |
              (
                (
                "-f"
                |
                "-required-flags"
                )
              "re#\w+"
              )
          }
        )
    |
    ()
    }
  $
  )
 ; 
