start = 
  (
  "gzip" /\s*/
    {
        (
          (
          "-S" /\s*/
          |
          "--suffix" /\s*/
          )
        /\S+/ /\s*/
        )
    |
    /-[123456789cdfhklNnqrVv]+/ /\s*/
    |
    /--[A-Z-]+/ /\s*/
    |
    input_file:/\S+/ /\s*/
    }
  $
  )
 ; 
