start = 
  samtools | 
  samtools_00 | 
  samtools_01 | 
  samtools_02 | 
  samtools_03 ;

samtools = "samtools" /\s+/ "view" { /\s+/ viewoptions} /\s+/ inputfile { /\s+/
    regions} $ ;

samtools_00 = "samtools" /\s+/ "flagstat" /\s+/ inputfile $ ;

samtools_01 = "samtools" /\s+/ "index" /\s+/ inputfile $ ;

samtools_02 = "samtools" /\s+/ "merge" /\s+/ outputfile /\s+/ inputfile { /\s+/
    inputfile} $ ;

samtools_03 = "samtools" /\s+/ "sort" { /\s+/ sortoptions} /\s+/ inputfile /\s+/
    outprefix $ ;

(* options *)
sortoptions = (
  sortoptions_flag
  | "-l" /\s+/ compression_level+:int
  | "-@" /\s+/ no_threads+:int
  | "-m" /\s+/ thread_memory+:string
  ) ; 

sortoptions_flag = "-" { sort_by_reada+:"n"
        | prefix_is_fullname+:"f"
        | output_to_stdout+:"o" }+;

(* options *)
viewoptions = (
  viewoptions_flag
  | "-@" /\s+/ int
  | "-L" /\s+/ bedoverlap
  | "-t" /\s+/ file
  | "-T" /\s+/ file
  | "-o" /\s+/ file
  | "-R" /\s+/ file
  | "-f" /\s+/ int
  | "-F" /\s+/ int
  | "-q" /\s+/ int
  | "-l" /\s+/ string
  | "-r" /\s+/ string
  | "-s" /\s+/ frac_subsample+:float
  ) ; 

viewoptions_flag = "-" { output_is_bam+:"b"
        | output_header+:"h"
        | "H"
        | input_is_sam+:"S"
        | "u"
        | "1"
        | "x"
        | "X"
        | "c"
        | "B"
        | "?" }+;


(* files *)
outputfile = outputfile+:/\S+\.bam/ ; 
inputfile = inputfile+:/\S+\.[bs]am/ ; 
bedoverlap = bedoverlap+:file ; 



(* other *)
regions = regions+:/\S+/ ; 
outprefix = outprefix+:/\S+/ ; 
sort_dasho = sort_dasho+:"-o" ; 


(* Misc *)
file = /\S+/ ;
path = file ; 
int = /[0-9]+/ ;
integer = int ;
float = /[0-9\.]+/ ;
string = ( /"[^"]*"/ | /'[^']*'/ | /\S+/ ) ;
str = string ;
